### ISSUE TITLE
Install error!

### ISSUE THREAD

**Issue by zzs1852** [bhklab/PymRMRe#1]
It failed when i **pip install Pymrmre**,
python 3.6.10
Cython 0.29.15
numpy 1.18.1
pandas 1.0.1
 /home/deeplearning/anaconda3/envs/py36/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/deeplearning/code/zzs/PymRMRe-master/pymrmre/expt/expt.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running install
running bdist_egg
running egg_info
......
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
error: command 'gcc' failed with exit status 1

**Comment by ChristopherEeles** [comment]
It looks like your C++ compiler is too old and does not include the c++11 standard.

What operating system are you running?

What version of that operating system?

Can you check your GCC version?

**Comment by zzs1852** [comment]
yeah!
as i updated gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) to gcc version 10.1.0 (GCC), it works,thx!

**Comment by ChristopherEeles** [comment]
Glad you were able to resolve the problem.

Best,
Chris
